config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :microposts do
    get 'report' => 'microposts#report'
  end
  resources :reported_comments
  resources :relationships, only: [:create, :destroy]
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  belongs_to :category, optional: true
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size
  has_many :reported_comments, dependent: :destroy

  scope :reported, ->{ where(reported: true) }
  scope :blocked, ->{ where(blocked: true) }
  scope :correct, ->{ where(blocked: false) }

  private

  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'should be less than 5 MB')
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :report, :update]
  before_action :correct_user, only: :destroy
  def create
    @micropost = current_user.microposts.build(microposts_params)
    if @micropost.save
      flash[:success] = t'flash.microposts.created'
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = t'flash.microposts.delete'
    redirect_to request.referrer || root_url
  end

  def report
    @micropost = Micropost.find_by(id: params[:micropost_id])
    @reported_comment = @micropost.reported_comments.build
  end

  private

  def microposts_params
    params.require(:micropost).permit(:content, :category_id, :picture, :blocked, :reported)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end 

app/helpers/microposts_helper.rb
module MicropostsHelper

  def create_select_for_category
    Category.all.map do |cat|
      [proper_category_language(cat), cat.id]
    end.push([t('category.no_category'),nil]).reverse!
  end
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to avatar_for(micropost.user), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <i> <%= t('category.category')%>
    <% if micropost.category %>
      <%= proper_category_language(micropost.category) %>
    <% else %>
      <%= t('category.no_category') %>
    <% end %>
    </i><br>
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    <%= t('time_ago', time: time_ago_in_words(micropost.created_at)) %>
    <% if current_user?(micropost.user) %>
      <%= link_to t('microposts.delete'), micropost, method: :delete, data: { confirm: t('microposts.confirm_del') } %>
      <p class='blocked'> <%= t("blocked.alert") if micropost.blocked %> </p> 
    <% else %> 
      <%= link_to t('report.button'), micropost_report_path(micropost) %>
    <% end %>
  </span>
</li> 

app/views/microposts/report.html.erb
<h1> <%= t('report.head')%> </h1>
<p> <%= t('report.question')%> <p>
<%= render 'shared/report_post_form'%>